### PR TITLE
Generic driver

### PR DESCRIPTION
**Pull request by zshaheen**
* new driver is `acme_driver.py`
* all plots are in plot folder
* project directory restructured
* `set` keyword added
* all plotting (including user plots) are handled by `acme_diags.plot` module
* more tests

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Nice! I will try it out today:)

**Comment by zshaheen** [comment]
Thanks Jill! I just realized plot set 7 isn't plotting polar, so I'll look at that. But it seems like set 5 is good. I'm also working on the viewer to add multiple pages when we have multiple set runs.

**Comment by zshaheen** [comment]
@chengzhuzhang I'm dumb and didn't make the regions to polar on my test. Plot set 7 works for vcs.

**Comment by chengzhuzhang** [comment]
@zshaheen Cool! Glad this is fixed easily:)

**Pull request merged**
